require 'spec_helper'

describe AccessSchema::ProxyLogger do

  describe ".debug" do

    before do
      @logger = AccessSchema::TestLogger.new
      @proxy = AccessSchema::ProxyLogger.new(@logger)
    end

    it "adds 'AccessSchema: ' prefix to passed message" do
      @proxy.debug("message test")
      @logger.output.should == "AccessSchema: message test"
    end

    it "adds the same prefix to message generated by passed block" do
      @proxy.debug{ "block test" }
      @logger.output.should == "AccessSchema: block test"
    end

  end

end

